name: Ablandscaping
favicon: null
layout_spectrum: 0.11261
typography_spectrum: 0.98372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#f9edd7'
    - '#dccbb1'
    - '#544339'
    - '#8e8774'
  brandStrength: 0.75
  lightness: 0.6662634159438312
  saturation: 0.375
  rhythmicContrast: 0.3508797609247267
purpose: []
