name: Ablandscaping
favicon: null
layout_spectrum: 0.22653
typography_spectrum: 0.98372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9e5f1'
    - '#43434b'
    - '#b4acaa'
    - '#9d7262'
    - '#1c202b'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
