name: Ablandscaping
favicon: null
layout_spectrum: 0.11261
typography_spectrum: 0.98372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1d1d1'
    - '#717171'
    - '#393939'
    - '#cb646f'
  brandStrength: 0.75
  lightness: 0.6662634159438312
  saturation: 0.4375
  rhythmicContrast: 0.3508797609247267
purpose: []
