name: Ablandscaping
favicon: null
layout_spectrum: 0.22653
typography_spectrum: 0.98372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cdcdcd'
    - '#706f74'
    - '#d28241'
    - '#c1414c'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
